sudo: required
servies:
  - docker

before_install:
  - docker build -t craytee/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true craytee/react-test npm test

after_success:
  - docker build -t craytee/multi-client ./client
  - docker build -t craytee/multi-nginx ./nginx
  - docker build -t craytee/multi-server ./server
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push craytee/multi-client
  - docker push craytee/multi-nginx
  - docker push craytee/multi-server

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: mt-docker
  env: MtDocker-env
  bucket_name: elasticbeanstalk-us-east-2-739683147855
  bucket_path: docker-mult
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
